{
 "title": "Mysterium Nodes",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Total earnings last 30 days in MYST",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myst_node_service_earnings)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total earnings last 30 days in EUR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myst_token_price{currency=\"EUR\"}) * sum(myst_node_service_earnings)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total traffic served last 30 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(myst_node_traffic)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total bandwidth",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(myst_node_bandwidth)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total traffic last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    { "expr": "myst_node_traffic", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total earnings last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "myst_node_service_earnings", "legendFormat": "{{name}}:{{service}}" }
   ]
  },
  {
   "title": "Total bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    { "expr": "myst_node_bandwidth", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Node details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(myst_node_monitoring_status) by (name, status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_version) by (name, version)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_external_ip) by (name, ip)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(myst_node_service_earnings) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_traffic) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_bandwidth) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_os) by (name, os)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_location) by (name, location)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_ip_category) by (name, category)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(myst_node_malicious) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}